<?php 
/**
 * ZF2 Buch Kapitel 12
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 12.28 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 12.28</h1>
<h3><code>UploadInputFilter</code> zum Filtern des Formulars</h3>
<pre>
&lt;?php
namespace Pizza\InputFilter;

use Zend\InputFilter\FileInput;
use Zend\InputFilter\Input;
use Zend\InputFilter\InputFilter;

class UploadInputFilter extends InputFilter
{
    public function __construct()
    {
        $name = new Input('upload_name');
        $name->getValidatorChain()->attachByName(
            'StringLength', 
            array('max' => 32)
        );
        $name->getFilterChain()->attachByName('StringTrim');
        $name->getFilterChain()->attachByName('Alpha');
        $name->getFilterChain()->attachByName('StringToLower');
        
        $file = new FileInput('upload_file');
        $file->setRequired(true);
        $file->getValidatorChain()->attachByName(
            'fileimagesize',
            array('maxWidth' => 150, 'maxHeight' => 150)
        );
        $file->getValidatorChain()->attachByName(
            'filemimetype',
            array('mimeType' => 'image/jpeg')
        );
        
        $this->add($name);
        $this->add($file);
    }
}
</pre>
</div>
</div>
