<?php 
/**
 * ZF2 Buch Kapitel 12
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 12.28 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 12.28</h1>
<h3>Anbindung von <code>PizzaEntity</code> an <code>AnotherPizzaForm</code></h3>
<pre>
&lt;?php
use Zend\Debug\Debug;
use Pizza\Entity\PizzaEntity;
use Pizza\Entity\PizzaHydrator;
use Pizza\Form\AnotherPizzaForm;
use Pizza\InputFilter\PizzaInputFilter;

$form = new AnotherPizzaForm;
$form->setHydrator(new PizzaHydrator());
$form->bind(new PizzaEntity());
$form->setInputFilter(new PizzaInputFilter());
$form->setData(array(
    'pizza_name'     => ' Pizza Gemüsegarten ',
    'pizza_price'    => '7.95',
    'pizza_category' => '2',
));
$form->isValid();

Debug::dump($form->getData());
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Debug\Debug;
use Pizza\Entity\PizzaEntity;
use Pizza\Entity\PizzaHydrator;
use Pizza\Form\AnotherPizzaForm;
use Pizza\InputFilter\PizzaInputFilter;

$form = new AnotherPizzaForm;
$form->setHydrator(new PizzaHydrator());
$form->bind(new PizzaEntity());
$form->setInputFilter(new PizzaInputFilter());
$form->setData(array(
    'pizza_name'     => ' Pizza Gemüsegarten ',
    'pizza_price'    => '7.95',
    'pizza_category' => '2',
));
$form->isValid();

Debug::dump($form->getData());
?>
</div>
</div>