<?php 
/**
 * ZF2 Buch Kapitel 12
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 12.26 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 12.26</h1>
<h3><code>PizzaEntity</code> mit Annotationen für Formulargenerierung</h3>
<pre>
&lt;?php
namespace Pizza\Entity;

use Zend\Form\Annotation;

/**
 * @Annotation\Name("annotation_pizza")
 * @Annotation\Attributes({"class":"form_horizontal"})
 */
class PizzaEntity
{
    /**
     * @Annotation\Type("Zend\Form\Element\Text")
     * @Annotation\Required({"required":"true"})
     * @Annotation\Filter({"name":"StringTrim"})
     * @Annotation\Validator({"name":"StringLength", "options":{"max":32}})
     * @Annotation\Validator({"name":"Alpha", "options":
     *                                        {"allowWhiteSpace":"true"}})
     * @Annotation\Attributes({"class":"span6"})
     * @Annotation\Options({"label":"Pizzaname:"})
     */
    protected $name;
    
    /**
     * @Annotation\Type("Zend\Form\Element\Text")
     * @Annotation\Required({"required":"true"})
     * @Annotation\Filter({"name":"NumberFormat"})
     * @Annotation\Validator({"name":"Float"})
     * @Annotation\Attributes({"class":"span6"})
     * @Annotation\Options({"label":"Preis:"})
     */
    protected $price;
    
    /**
     * @Annotation\Type("Zend\Form\Element\Select")
     * @Annotation\Validator({"name":"InArray", "options":
     *                                          {"haystack":{"1","2","3"}}})
     * @Annotation\Attributes({"class":"span6"})
     * @Annotation\Options({"label":"Kategorie:",
     *                      "value_options":{"1":"Klassiker",
     *                                       "2":"Vegetarisch",
     *                                       "3":"Extravagant"}})
     */
    protected $category;
    
    /**
     * @Annotation\Type("Zend\Form\Element\Submit")
     * @Annotation\AllowEmpty()
     * @Annotation\Attributes({"value":"Pizza speichern"})
     * @Annotation\Attributes({"class":"btn"})
     */
    protected $submit;
    
    public function setName($name)
    {
        $this->name = $name;
    }
    
    public function getName()
    {
        return $this->name;
    }
    
    public function setPrice($price)
    {
        $this->price = $price;
    }
    
    public function getPrice()
    {
        return round($this->price, 2);
    }
    
    public function setCategory($category)
    {
        $this->category = $category;
    }
    
    public function getCategory()
    {
        return $this->category;
    }
}
</pre>
</div>
</div>
