<?php 
/**
 * ZF2 Buch Kapitel 12
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 12.12 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 12.12</h1>
<h3><code>ToppingsRowFieldset</code> stellt Fieldset für Pizzabeläge bereit</h3>
<pre>
&lt;?php
namespace Pizza\Form;

use Zend\Form\Element\Select;
use Zend\Form\Fieldset;

class ToppingsRowFieldset extends Fieldset
{
    public function __construct()
    {
        parent::__construct('toppings_row');
        
        $toppingElement = new Select('pizza_topping_id');
        $toppingElement->setLabel('Pizzabelag');
        $toppingElement->setValueOptions(array(
            1 => 'Tomatenpampe',  2 => 'Käse',      3 => 'Salami',
            4 => 'Schinken',      5 => 'Ananas',    6 => 'Champignons',
            7 => 'Melone',        8 => 'Zwiebeln',  9 => 'Thunfisch',
            10 => 'Spinat',      11 => 'Peperoni', 12 => 'Feta',
            13 => 'Hackfleisch', 14 => 'Mais',
        ));

        $portionElement = new Select('pizza_topping_portion');
        $portionElement->setLabel('Portion');
        $portionElement->setValueOptions(array(
            0 => '0', 1 => '1', 2 => '2', 3 => '3',
        ));

        $this->add($toppingElement);
        $this->add($portionElement);
    }
}
</pre>
</div>
</div>
