<?php 
/**
 * ZF2 Buch Kapitel 12
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 12.19 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 12.19</h1>
<h3>HTML-Code für die Ausgabe vom <code>SimplePizzaForm</code></h3>
<pre>
&lt;form action="" method="POST" name="simple_pizza" id="simple_pizza"&gt;
&lt;label&gt;
&lt;span&gt;Pizzaname&lt;/span&gt;
&lt;input type="text" name="pizza_data[pizza_name]" value=""&gt;
&lt;/label&gt;
&lt;label&gt;
&lt;span&gt;Preis&lt;/span&gt;
&lt;input type="text" name="pizza_data[pizza_price]" value=""&gt;
&lt;/label&gt;
&lt;label&gt;
&lt;span&gt;Kategorie&lt;/span&gt;
&lt;select name="pizza_data[pizza_category]"&gt;
&lt;option value="1"&gt;Klassiker&lt;/option&gt;
&lt;option value="2"&gt;Vegetarisch&lt;/option&gt;
&lt;option value="3"&gt;Extravagant&lt;/option&gt;
&lt;/select&gt;
&lt;/label&gt;
&lt;input type="submit" name="save_pizza" value="Pizza speichern"&gt;
&lt;/form&gt;
</pre>
</div>
</div>
