<?php 
/**
 * ZF2 Buch Kapitel 12
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 12.15 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 12.15</h1>
<h3>Ausgabe von <code>SimplePizzaForm</code> mit <code>Form</code> und <code>FormRow</code> View-Helpern</h3>
<pre>
&lt;?php
use Pizza\Form\SimplePizzaForm;
use Pizza\Form\PizzaDataFieldset;

$form = new SimplePizzaForm(new PizzaDataFieldset());
$form->prepare();

$this->headStyle()->appendStyle('label { width: 200px; }');

echo $this->form()->openTag($form);
foreach ($form->get('pizza_data') as $element) {
    echo $this->formRow($element);
}
echo $this->formRow($form->get('save_pizza'));
echo $this->form()->closeTag();
</pre>
<h3>Ausgabe</h3>
<div class="well">
<?php 
use Pizza\Form\SimplePizzaForm;
use Pizza\Form\PizzaDataFieldset;

$form = new SimplePizzaForm(new PizzaDataFieldset());
$form->prepare();

$this->headStyle()->appendStyle('label { width: 200px; }');

echo $this->form()->openTag($form);
foreach ($form->get('pizza_data') as $element) {
    echo $this->formRow($element);
}
echo $this->formRow($form->get('save_pizza'));
echo $this->form()->closeTag();
?>
</div>
</div>
</div>
