<?php 
/**
 * ZF2 Buch Kapitel 12
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 12.9 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 12.9</h1>
<h3><code>PizzaDataFieldset</code> stellt Fieldset für Pizzadaten bereit</h3>
<pre>
&lt;?php
namespace Pizza\Form;

use Zend\Form\Element\Select;
use Zend\Form\Element\Text;
use Zend\Form\Fieldset;

class PizzaDataFieldset extends Fieldset
{
    public function __construct()
    {
        parent::__construct('pizza_data');
        
        $this->setLabel('Pizzadaten');
        
        $nameElement = new Text('pizza_name');
        $nameElement->setLabel('Pizzaname');
        
        $priceElement = new Text('pizza_price');
        $priceElement->setLabel('Preis');
        
        $categoryElement = new Select('pizza_category');
        $categoryElement->setLabel('Kategorie');
        $categoryElement->setValueOptions(array(
            1 => 'Klassiker', 2 => 'Vegetarisch', 3 => 'Extravagant'
        ));
        
        $this->add($nameElement);
        $this->add($priceElement);
        $this->add($categoryElement);
    }
}
</pre>
</div>
</div>
