<?php 
/**
 * ZF2 Buch Kapitel 12
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 12.8 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 12.8</h1>
<h3>Formular mit Fieldsets durch <code>Zend\Form\Factory</code> generieren</h3>
<pre>
&lt;?php
use Zend\Form\Factory;

$factory = new Factory();

$form = $factory->createForm(array(
    'fieldsets' => array(
        array(
            'spec' => array(
                'name'  => 'data',
                'options' => array('label' => 'Pizzadaten'),
                'elements' => array(
                    array(
                        'spec' => array(
                            'type'    => 'Zend\Form\Element\Text',
                            'name'    => 'pizza_name',
                            'options' => array('label' => 'Pizzaname'),
                        ),
                    ),
                    array(
                        'spec' => array(
                            'type'    => 'Zend\Form\Element\Text',
                            'name'    => 'pizza_price',
                            'options' => array('label' => 'Preis'),
                        ),
                    ),
                    array(
                        'spec' => array(
                            'type'    => 'Zend\Form\Element\Select',
                            'name'    => 'pizza_category',
                            'options' => array(
                                'label' => 'Kategorie',
                                'value_options' => array(
                                    1 => 'Klassiker', 2 => 'Vegetarisch', 
                                    3 => 'Extravagant'
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    'elements' => array(
        array(
            'spec' => array(
                'type'       => 'Zend\Form\Element\Submit',
                'name'       => 'save_pizza',
                'attributes' => array('value' => 'Pizza speichern'),
            ),
        ),
    ),
));
</pre>
<h3>Ausgabe</h3>
<div class="well">
<?php 
use Zend\Form\Factory;

$factory = new Factory();

$form = $factory->createForm(array(
    'fieldsets' => array(
        array(
            'spec' => array(
                'name'  => 'data',
                'options' => array('label' => 'Pizzadaten'),
                'elements' => array(
                    array(
                        'spec' => array(
                            'type'    => 'Zend\Form\Element\Text',
                            'name'    => 'pizza_name',
                            'options' => array('label' => 'Pizzaname'),
                        ),
                    ),
                    array(
                        'spec' => array(
                            'type'    => 'Zend\Form\Element\Text',
                            'name'    => 'pizza_price',
                            'options' => array('label' => 'Preis'),
                        ),
                    ),
                    array(
                        'spec' => array(
                            'type'    => 'Zend\Form\Element\Select',
                            'name'    => 'pizza_category',
                            'options' => array(
                                'label' => 'Kategorie',
                                'value_options' => array(
                                    1 => 'Klassiker', 2 => 'Vegetarisch', 
                                    3 => 'Extravagant'
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    'elements' => array(
        array(
            'spec' => array(
                'type'       => 'Zend\Form\Element\Submit',
                'name'       => 'save_pizza',
                'attributes' => array('value' => 'Pizza speichern'),
            ),
        ),
    ),
));

$form->prepare();

$this->headStyle()->appendStyle('label { width: 200px; }'); 
?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formCollection($form->get('data')); ?>
<?php echo $this->formRow($form->get('save_pizza')); ?>
<?php echo $this->form()->closeTag(); ?>
</div>
</div>
</div>
