<?php 
/**
 * ZF2 Buch Kapitel 12
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 12.25 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 12.25</h1>
<h3><code>composer.json</code> für Installation von Doctrine/Common</h3>
<pre>
{
    "name": "zf2buch/kapitel12",
    "description": "Listings für Kapitel 12 vom Zend Framework 2 Buch",
    "keywords": [
        "framework",
        "zf2"
    ],
    "homepage": "http://www.zendframeworkbuch.de/",
    "require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.1.*",
        "doctrine/common" : ">=2.1"
    }
}
</pre>
</div>
</div>
